version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank_user -d bank_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_db
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_pass
      JWT_SECRET: YzJmNDNkMGY4ZjE1ZDExZTgxZDRjNzYwN2E1ZDRkZGE5OTYxNzZhY2U0YmVhNzE0ZTc1N2E3ZDk4ZmU1ZjQ2ZQ==
    ports:
      - "8080:8080"
    networks:
      - bank_network

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge