version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - bank_network

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge